{{- if and .Values.auth.ldap.enabled .Values.auth.ldap.bindPasswordSecretCreate .Values.auth.ldap.bindPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.ldap.bindPasswordSecret }}
  labels:
{{ include "impala.labels" . | indent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.ldap.bindPasswordKey }}: {{ .Values.auth.ldap.bindPassword | quote }}
{{- end }}
