apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "impala.fullname" . }}-statestored
  labels:
{{ include "impala.labels" . | indent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "impala.fullname" . }}-statestored
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "impala.name" . }}
      app.kubernetes.io/component: statestored
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "impala.name" . }}
        app.kubernetes.io/component: statestored
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
        - name: statestored
          image: {{ include "impala.image" (dict "Values" .Values "imageName" "statestored") }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -redirect_stdout_stderr=false
            - -logtostderr
            - -v=1
{{- if .Values.auth.tls.enabled }}
            - -ssl_server_certificate=/etc/impala/tls/{{ .Values.auth.tls.certFile }}
            - -ssl_private_key=/etc/impala/tls/{{ .Values.auth.tls.keyFile }}
{{- if .Values.auth.tls.caFile }}
            - -ssl_client_ca_certificate=/etc/impala/tls/{{ .Values.auth.tls.caFile }}
{{- end }}
{{- end }}
{{- range .Values.statestored.extraArgs }}
            - {{ . | quote }}
{{- end }}
          ports:
            - name: rpc
              containerPort: 24000
            - name: web
              containerPort: 25010
          volumeMounts:
            - name: conf
              mountPath: /opt/impala/conf/hive-site.xml
              subPath: hive-site.xml
{{- if .Values.auth.tls.enabled }}
            - name: tls
              mountPath: /etc/impala/tls
              readOnly: true
{{- end }}
      volumes:
        - name: conf
          configMap:
            name: {{ include "impala.fullname" . }}-conf
{{- if .Values.auth.tls.enabled }}
        - name: tls
          secret:
            secretName: {{ .Values.auth.tls.secretName }}
{{- end }}